version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dotnet-mongodb
      MONGO_INITDB_ROOT_HOST: localhost
      MONGO_INITDB_ROOT_PORT: 27017
      MONGO_INITDB_ROOT_AUTH_SOURCE: admin
